# Generated by Django 6.0.5 on 2026-07-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_combo_elementocombo_presentacionproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto o Aporte Inicial de Caja')),
            ],
        ),
    ]
