# Generated by Django 6.0.5 on 2026-07-28 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_configuracioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncaja',
            name='fecha_inicio_caja',
            field=models.DateField(default=datetime.date(2026, 6, 13), verbose_name='Fecha Inicio Control de Caja'),
        ),
        migrations.AlterField(
            model_name='configuracioncaja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto o Aporte Inicial Adicional de Caja'),
        ),
    ]
