# Generated by Django 6.0.5 on 2026-07-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_remove_venta_estado_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
