# Generated by Django 6.0.7 on 2026-07-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='valor_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
