# Generated by Django 6.0.7 on 2026-07-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permitir_editar_eliminar', models.BooleanField(default=True, verbose_name='Permitir editar o eliminar compras')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_envio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
